TARGET_FUNCTIONS = ['onex_parser_page', 'chatterfy_parser_page']

MODULE_SOURCE = 'def onex_parser_page(\n    request: Request,\n    account_id: str = Query(default=""),\n    period_label: str = Query(default=""),\n    search: str = Query(default=""),\n    message: str = Query(default=""),\n):\n    user = get_current_user(request)\n    if not user:\n        return auth_redirect_response()\n    enforce_page_access(user, "onexparser")\n    rows = get_onex_parser_rows(account_id=account_id, period_label=period_label, search=search)\n    return onex_parser_page_html(\n        user,\n        rows,\n        account_id=account_id,\n        period_label=period_label,\n        search=search,\n        success_text=message,\n    )\n\ndef chatterfy_parser_page(\n    request: Request,\n    status: str = Query(default=""),\n    search: str = Query(default=""),\n    date_filter: str = Query(default=""),\n    time_filter: str = Query(default=""),\n    telegram_id: str = Query(default=""),\n    page: int = Query(default=1),\n    bot_url: str = Query(default=""),\n    email: str = Query(default=""),\n    date_start: str = Query(default=CHATTERFY_PARSER_DEFAULT_START),\n    date_end: str = Query(default=CHATTERFY_PARSER_DEFAULT_END),\n    message: str = Query(default=""),\n):\n    user = get_current_user(request)\n    if not user:\n        return auth_redirect_response()\n    enforce_page_access(user, "chatterfyparser")\n    rows = get_chatterfy_parser_rows(\n        status=status,\n        search=search,\n        date_filter=date_filter,\n        time_filter=time_filter,\n        telegram_id=telegram_id,\n    )\n    per_page = 100\n    page = max(1, int(page or 1))\n    start = (page - 1) * per_page\n    page_rows = rows[start:start + per_page]\n    return chatterfy_parser_page_html(\n        user,\n        page_rows,\n        form_data={\n            "bot_url": bot_url,\n            "email": email,\n            "date_start": date_start,\n            "date_end": date_end,\n        },\n        status=status,\n        search=search,\n        date_filter=date_filter,\n        time_filter=time_filter,\n        telegram_id=telegram_id,\n        page=page,\n        total_count=len(rows),\n        per_page=per_page,\n        success_text=message,\n    )\n\n'


def bind_domain_routes(ctx):
    scope = dict(ctx)
    exec(MODULE_SOURCE, scope)
    return {name: scope[name] for name in TARGET_FUNCTIONS}
